In [2]:
import numpy as np

A = np.array([[56.0,0.0,4.4,68.0],
             [1.2,104.0,52.0,8.0],
             [1.8,135.0,99.0,0.9]])
print(A)

[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]


In [3]:
cal = A.sum(axis=0)
cal

array([ 59. , 239. , 155.4,  76.9])

In [4]:
percentage = 100* A/cal.reshape(1,4)
percentage

array([[94.91525424,  0.        ,  2.83140283, 88.42652796],
       [ 2.03389831, 43.51464435, 33.46203346, 10.40312094],
       [ 3.05084746, 56.48535565, 63.70656371,  1.17035111]])

In [5]:
# Tips and Tricks
a = np.random.randn(5)
a # Create Rank 1 Array, Instead of these write explicitly
a = np.random.randn(5,1)
assert (a.shape == (5,1))

In [7]:
s = np.array([1,2,3,4])
s.shape

(4,)

In [15]:
s.reshape(1,4)

array([[1, 2, 3, 4]])

In [16]:
s.reshape(4,1)

array([[1],
       [2],
       [3],
       [4]])

In [18]:
a = np.array([1,2,3,4])
a[None,:]

array([[1, 2, 3, 4]])

In [19]:
a[:,None]

array([[1],
       [2],
       [3],
       [4]])